# Generated by Django 5.2.6 on 2026-05-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Food Name')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand')),
                ('category', models.CharField(blank=True, choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('proteins', 'Proteins'), ('carbs', 'Carbohydrates'), ('fats', 'Fats'), ('dairy', 'Dairy'), ('sweets', 'Sweets'), ('beverages', 'Beverages')], max_length=20, verbose_name='Category')),
                ('serving_size', models.CharField(default='100g', max_length=50, verbose_name='Serving Size')),
                ('calories', models.IntegerField(default=0, verbose_name='Calories')),
                ('protein', models.FloatField(default=0, verbose_name='Protein (g)')),
                ('carbs', models.FloatField(default=0, verbose_name='Carbs (g)')),
                ('fat', models.FloatField(default=0, verbose_name='Fat (g)')),
                ('fiber', models.FloatField(default=0, verbose_name='Fiber (g)')),
                ('sugar', models.FloatField(default=0, verbose_name='Sugar (g)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='foods_food_name_8eac09_idx'), models.Index(fields=['category'], name='foods_food_categor_1c1684_idx')],
            },
        ),
    ]
