#!/usr/bin/env python
# ===================================================================================================================
# FILE: manage.py
# PURPOSE: Django's command-line management utility — the MAIN ENTRY POINT for all server-side administrative tasks.
#          This file is auto-generated by Django when creating a project. It bootstraps the Django environment
#          and routes terminal commands to the correct internal Django management handler.
#
# HOW IT WORKS (step-by-step):
#   1. The developer types a command in the terminal, e.g.: python manage.py runserver
#   2. Python executes this file, calling main()
#   3. main() sets the DJANGO_SETTINGS_MODULE environment variable → tells Django which settings.py to use
#   4. Django's execute_from_command_line() reads sys.argv (the terminal arguments) and routes to the right handler
#
# COMMON COMMANDS:
#   python manage.py runserver          → Starts the local HTTP API server on http://127.0.0.1:8000/
#   python manage.py makemigrations    → Scans models.py files and auto-generates migration scripts for DB schema
#   python manage.py migrate            → Applies all pending migration files to the SQLite database (creates tables)
#   python manage.py createsuperuser   → Interactively creates an admin user to access the /admin panel
#   python manage.py collectstatic     → Gathers all static assets (CSS/JS) into STATIC_ROOT for production
#   python manage.py shell             → Opens an interactive Python shell with the Django environment loaded
# ===================================================================================================================

import os   # Standard library module: provides functions to interact with the operating system (env vars, paths)
import sys  # Standard library module: provides sys.argv — the list of terminal arguments (e.g. ['manage.py', 'runserver'])


def main():
    """
    Main function that bootstraps the Django environment and dispatches the management command.
    This is the first function called when `python manage.py <command>` is executed.
    """

    # Set the DJANGO_SETTINGS_MODULE environment variable so Django knows which settings.py file to load.
    # 'calal_backend.settings' → Python package path to calal_backend/settings.py
    # os.environ.setdefault() only sets the variable if it is NOT already set (avoids overwriting external config)
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'calal_backend.settings')

    try:
        # Dynamically import Django's command-line execution engine.
        # This import succeeds only if Django is installed in the current Python virtual environment (venv/).
        from django.core.management import execute_from_command_line

    except ImportError as exc:
        # If Django cannot be imported, raise a descriptive error with troubleshooting steps.
        # This catches the case where the developer forgot to activate the virtual environment.
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc

    # Pass sys.argv (the full terminal command) to Django's dispatcher.
    # Django reads sys.argv[1] (e.g. 'runserver', 'migrate') and calls the matching management command class.
    execute_from_command_line(sys.argv)


# Python standard guard: ensures main() is only called when this script is executed DIRECTLY from the terminal.
# If manage.py were imported by another module, main() would NOT be called automatically.
if __name__ == '__main__':
    main()
